title = "RustBlog"
base_url = "http://localhost:1111"
description = "A minimalist blog with Zola and Tailwind CSS"
default_language = "en"

taxonomies = [
  {name = "tags", paginate_by = 5},
  {name = "categories", paginate_by = 5},
]

[markdown]
highlight_code = true