title = "RustBlog"
base_url = "https://yoloinfinity55.github.io/rustblog"
description = "A blog with Zola and Tailwind CSS"
default_language = "en"
taxonomies = [
    {name = "tags", feed = true},
    {name = "categories", feed = true},
]
[markdown]
highlight_code = true
